### ISSUE TITLE
Problem on Uglify for production build

### ISSUE THREAD

**Issue by AndreyShpilevoy** [milesj/aesthetic#7] opened 2017-02-21 16:43 UTC
First of all, thank you for this awesome package. It's really cool package.

I use HOC for 4 my components, it's work as expected in development mode.
When I build project in production mode - 2 components receive the classNames object for property from another component.

If I disable webpack.optimize.UglifyJsPlugin from the production build - it also works as expected.

Link to my rep: [https://github.com/AndreyShpilevoy/DemUiBoilerplate/tree/master/DEM_MVC_UI](url)
I trying to create Bootstrap-like grid on jss with theme support.

**Comment by milesj** [comment] 2017-02-21 18:59
I haven't looked into it too much, but I believe the issue is that you're not using true functions for your components, but are using anonymous functions, like so:

```
const Container = ({ fluid, children, classNames }) =>
```

When Uglify is ran, I'm assuming this get's converted to something like `const a = () =>`, which is causing the duplicate style objects. I'd suggest using true functions, or passing a `styleName` to the styler function.

**Comment by AndreyShpilevoy** [comment] 2017-02-21 19:15
Thank you for the fast reply.
I tried to change my arrow functions to named functions but got the same result.
Unfortunately, the problem wasn't solved.

**Comment by AndreyShpilevoy** [comment] 2017-02-21 20:45
I also changed all those components from stateless to stateful - and even that didn't solve the problem with UglifyJsPlugin .

**Comment by milesj** [comment] 2017-02-22 05:33
Weird. Looking into it a bit more.

**Comment by milesj** [comment] 2017-02-22 07:30
Messed around with this a bit, the problem resolves itself if you pass `mangle: false` to the uglify configuration or if you use `options.styleName`. http://lisperator.net/uglifyjs/mangle

This is definitely a tricky situation to solve. I can probably generate a UID in production.

**Comment by AndreyShpilevoy** [comment] 2017-02-22 08:38
Yep, if pass `mangle: false` to the uglify configuration really solved this issue.
But it increased bundled files size average in 51,5%.
So it's definitely a workaround.

I will wait for your fix this problem.
Huge thank you for your time and great work.

**Comment by milesj** [comment] 2017-02-22 21:48
Thanks for finding the issue. Definitely something that should be fixed.

Will most likely go with the UID approach. Just need to avoid collisions.

**Comment by milesj** [comment] 2017-02-23 06:31
@AndreyShpilevoy I published a small patch, let me know if that works for you.

**Closed by milesj** 2017-02-23 06:31 UTC

**Comment by AndreyShpilevoy** [comment] 2017-02-23 08:32
Thank you!
It's really work. Even with stateless arrow functions.

**Comment by milesj** [comment] 2017-02-23 20:01
Sweet. 👍
